### ISSUE TITLE
Nuxt Tailwind Icon from preset not showing

### ISSUE THREAD

**Issue by frasza** [jcamp-code/nuxt-icon-tw#3]
Hey,

I found package since Nuxt Icon only provides option for icons to be loaded from API and it causes issues on our side where we want to show icons preferably loaded locally. That is why I believe Tailwind icons can be great.

Anyway, I tried the package and failed to get the results displaying the icon. I am using Tabler preset (https://www.npmjs.com/package/@iconify-json/tabler) and Icon component does not render.

Here is my reproduction:
https://github.com/frasza/nuxt-icon-tw

Maybe I am doing something wrong? 

Thanks!

**Comment by AndyL4N** [comment]
Hi, @frasza.  
I got the same issue. Just check an order of nuxt modules' definition. If you place it right as described in docs - it should work:
`export default defineNuxtConfig({
  modules: ['nuxt-icon-tw', '@nuxtjs/tailwindcss'],
})`

At least 'nuxt-icon-tw' should be defined before '@nuxtjs/tailwindcss'.

**Comment by ineshbose** [comment]
Seems like the order of module may have been the issue - but the latest version of `@nuxtjs/tailwindcss` should not care about module being registered before! (https://github.com/nuxt-modules/tailwindcss/issues/826) 🙂

**Comment by JohnCampionJr** [comment]
I do recommend putting `nuxt-icon-tw` before other modules, specifically anything that brings in `@nuxt/icon`.  We have the priority set so that our `<Icon>` component will get used in place of that one.  This allows us to take over for projects that use Tailwind and `@nuxt/icon` like nuxt-ui.
